create table
  public.users (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    uid text not null,
    is_admin boolean not null default false,
    accepted_events json not null default '[]'::json,
    rejected_events json not null default '[]'::json,
    undecided_events json not null default '[]'::json,
    selected_event_filter text not null default 'ALL'::text,
    constraint users_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.events (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    title text not null,
    details text null,
    location_name text null,
    location_address text null,
    created_by_user_id text not null,
    start_date timestamp with time zone not null,
    end_date timestamp with time zone null,
    is_cancelled boolean not null default false,
    event_type text not null default 'OTHER'::text,
    constraint events_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.dms (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    expiry_date timestamp with time zone null,
    user_uid text not null,
    channel_id text not null,
    timestamp text not null,
    event_id numeric null,
    constraint dms_pkey primary key (id)
  ) tablespace pg_default;